### ISSUE TITLE
Boomerang Bottom missing the Navy variant image

### ISSUE THREAD

**Issue by michaelburtonray** [human-nyc/tropicofc#62]
https://tropicofc.myshopify.com/collections/bottoms/products/splash-bottom

**Comment by michaelburtonray** [comment]
[boomerang bottom.mp4.zip](https://github.com/human-nyc/tropicofc/files/1712014/boomerang.bottom.mp4.zip)

**Comment by sashakluchnik** [comment]
it's not missing
